# Generated by Django 4.0.4 on 2022-06-02 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='site',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
