# Generated by Django 4.0.4 on 2022-06-03 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.IntegerField(choices=[(1, 'Cart'), (2, 'Realized'), (3, 'Paid'), (4, 'Delivered')], default=1),
        ),
    ]
