# Generated by Django 4.0.4 on 2022-06-01 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_uuid',
            new_name='id',
        ),
    ]
