# Generated by Django 4.0.4 on 2022-06-01 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_user_uuid_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='id',
            new_name='user_uuid',
        ),
    ]
